// Code generated by MockGen. DO NOT EDIT.
// Source: parking.go
//
// Generated by this command:
//
//	mockgen -source=parking.go -destination=../mock/mock_parking/parking.go -package=mockparking
//

// Package mockparking is a generated GoMock package.
package mockparking

import (
	model "parkingLot/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockParkingItf is a mock of ParkingItf interface.
type MockParkingItf struct {
	ctrl     *gomock.Controller
	recorder *MockParkingItfMockRecorder
	isgomock struct{}
}

// MockParkingItfMockRecorder is the mock recorder for MockParkingItf.
type MockParkingItfMockRecorder struct {
	mock *MockParkingItf
}

// NewMockParkingItf creates a new mock instance.
func NewMockParkingItf(ctrl *gomock.Controller) *MockParkingItf {
	mock := &MockParkingItf{ctrl: ctrl}
	mock.recorder = &MockParkingItfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingItf) EXPECT() *MockParkingItfMockRecorder {
	return m.recorder
}

// AddCar mocks base method.
func (m *MockParkingItf) AddCar(ps *model.ParkingSystem, car *model.Car) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCar", ps, car)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCar indicates an expected call of AddCar.
func (mr *MockParkingItfMockRecorder) AddCar(ps, car any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCar", reflect.TypeOf((*MockParkingItf)(nil).AddCar), ps, car)
}

// CheckCarExist mocks base method.
func (m *MockParkingItf) CheckCarExist(car *model.Car) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCarExist", car)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCarExist indicates an expected call of CheckCarExist.
func (mr *MockParkingItfMockRecorder) CheckCarExist(car any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCarExist", reflect.TypeOf((*MockParkingItf)(nil).CheckCarExist), car)
}

// GetCar mocks base method.
func (m *MockParkingItf) GetCar(ps *model.ParkingSystem, ticket string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCar", ps, ticket)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCar indicates an expected call of GetCar.
func (mr *MockParkingItfMockRecorder) GetCar(ps, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCar", reflect.TypeOf((*MockParkingItf)(nil).GetCar), ps, ticket)
}

// GetMaximum mocks base method.
func (m *MockParkingItf) GetMaximum() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaximum")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaximum indicates an expected call of GetMaximum.
func (mr *MockParkingItfMockRecorder) GetMaximum() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaximum", reflect.TypeOf((*MockParkingItf)(nil).GetMaximum))
}

// GetName mocks base method.
func (m *MockParkingItf) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockParkingItfMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockParkingItf)(nil).GetName))
}
