// Code generated by MockGen. DO NOT EDIT.
// Source: subject.go
//
// Generated by this command:
//
//	mockgen -source=subject.go -destination=../mock/mock_subject/subject.go -package=mocksubject
//

// Package mocksubject is a generated GoMock package.
package mocksubject

import (
	observer "parkingLot/observer"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubject is a mock of Subject interface.
type MockSubject struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectMockRecorder
	isgomock struct{}
}

// MockSubjectMockRecorder is the mock recorder for MockSubject.
type MockSubjectMockRecorder struct {
	mock *MockSubject
}

// NewMockSubject creates a new mock instance.
func NewMockSubject(ctrl *gomock.Controller) *MockSubject {
	mock := &MockSubject{ctrl: ctrl}
	mock.recorder = &MockSubjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubject) EXPECT() *MockSubjectMockRecorder {
	return m.recorder
}

// Deregister mocks base method.
func (m *MockSubject) Deregister(arg0 observer.Observer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Deregister", arg0)
}

// Deregister indicates an expected call of Deregister.
func (mr *MockSubjectMockRecorder) Deregister(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deregister", reflect.TypeOf((*MockSubject)(nil).Deregister), arg0)
}

// NotifyAll mocks base method.
func (m *MockSubject) NotifyAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyAll")
}

// NotifyAll indicates an expected call of NotifyAll.
func (mr *MockSubjectMockRecorder) NotifyAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAll", reflect.TypeOf((*MockSubject)(nil).NotifyAll))
}

// Register mocks base method.
func (m *MockSubject) Register(arg0 observer.Observer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", arg0)
}

// Register indicates an expected call of Register.
func (mr *MockSubjectMockRecorder) Register(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockSubject)(nil).Register), arg0)
}
